public enum Position {
    DIRECTOR, CHIEF_ENGINEER, ACCOUNTANT, HUMAN_RELATIONS_MANAGER, OFFICE_MANAGER,
    INTERPRETER, PURCHASE_MANAGER, SALES_MANAGER, PUBLIC_RELATIONS_MANAGER,
    RESEARCH_AND_DEVELOPMENT_MANAGER, WORKER, PORTER, DRIVER
}
